### ISSUE TITLE
Incompatible with Terraform 0.7.3

### ISSUE THREAD

**Issue by jonasschmidt** [terraform-community-modules/tf_aws_virttype#2]
The module does not work with the variable handling changes introduced in Terraform `0.7.3`. In the Terraform change log it sounds like variables and outputs can't use the same name anymore. When I run a `terraform plan` for this module with `0.7.3` it asks for the values of `var.prefer_hvm` and `var.prever_pv`.

**Comment by nathan-muir** [comment]
Had a look at this, appears to be a JSON key issue hashicorp/terraform#5140 (that will be fixed in 0.7.4)

Adding a description to the variables seems to get around the issue [https://github.com/3stack-software/tf_aws_virttype/commit/a7baba8cf4abe265dbe28dc6f5c3ed1db35b30c1]

**Comment by bsiegel** [comment]
Running Terraform v0.7.4-dev built from HEAD this morning, and I still have this issue:

> Error loading Terraform: module virttype: required variable prefer_pv not set

**Comment by antonbabenko** [comment]
I think I have just fixed it in #3 . Thanks everyone!
